// Build-time step: bundle kb/docs/*.md into a single grounding module the chat
// function imports. The whole KB fits in a model's context window, so there is
// no retrieval and no embeddings — the entire knowledge base rides in the system
// prompt (the simple-proxy shape shared with the Nice Vibe and HEB Prep apps).
//
// Run locally after any KB change: `node scripts/build-kb.mjs`. It writes the
// committed netlify/functions/kb.js, so no build step runs on the host. That
// keeps deploys instant and immune to a host's build-minute ceiling.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS_DIR = join(ROOT, 'kb', 'docs');
const OUT = join(ROOT, 'netlify', 'functions', 'kb.js');

// Pull the frontmatter fields we need, without a YAML dependency.
function parseDoc(raw, filename) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  const front = m ? m[1] : '';
  const body = (m ? m[2] : raw).trim();
  const field = (name) => {
    const line = front.match(new RegExp(`^${name}:\\s*(.+)$`, 'm'));
    return line ? line[1].trim().replace(/^["']|["']$/g, '') : '';
  };
  return {
    id: field('id') || filename.replace(/\.md$/, ''),
    title: field('title') || filename,
    category: field('category'),
    source_url: field('source_url'),
    body,
  };
}

const files = readdirSync(DOCS_DIR).filter((f) => f.endsWith('.md')).sort();
const docs = files.map((f) => parseDoc(readFileSync(join(DOCS_DIR, f), 'utf8'), f));

// One flat grounding string. Each doc is fenced with its title (and source URL,
// so the assistant can name where an answer comes from) and its full body.
const KB_TEXT = docs
  .map((d) => {
    const src = d.source_url ? `\n(Source document: ${d.title}${d.source_url ? ` — ${d.source_url}` : ''})` : `\n(Source document: ${d.title})`;
    return `===== ${d.title} =====${src}\n\n${d.body}`;
  })
  .join('\n\n');

// A short catalog the assistant can offer by name ("that's covered in …").
const SOURCES = docs.map((d) => ({ id: d.id, title: d.title, url: d.source_url }));

const out =
  '// Generated by scripts/build-kb.mjs from kb/docs. Do not hand-edit.\n' +
  '// The knowledge the chat function grounds on. Regenerate when docs change.\n' +
  `module.exports = {\n  KB_TEXT: ${JSON.stringify(KB_TEXT)},\n  SOURCES: ${JSON.stringify(SOURCES)},\n};\n`;

writeFileSync(OUT, out);
console.log(`wrote netlify/functions/kb.js — ${docs.length} docs, KB_TEXT ${KB_TEXT.length} chars (~${Math.round(KB_TEXT.length / 4000)}k tokens)`);
